input:
  dataset:
    src: "MNIST"
    tgts: ["MNISTM"]
    transformation :
        img_size: 28 # size of input if images input
        src : transform_mnist # name of the transform to perform on train data
        tgt : transform_mnistm # name of the transform to perform on train data
        mean: [0.485, 0.456, 0.406] # mean used for normalization (from resnet34)
        std: [0.229, 0.224, 0.225] # std used for normalization (from resnet34)

model:
  type : MADA
  backbone: resnet34
  pretrained_backbone: imagenet
  n_layers_freeze: 0
  class_classifier: linear2_bn
  domain_classifier: linear2_bn

training:
  gpus: 1
  num_workers: 4
  optimizer:
    type: Adam
    momentum: 0.9
    lr: 0.0001
    weight_decay: 2.5e-5
  scheduler:
    lr_schedule: true
    alpha: 10
    gamma: 10
    beta: 0.75
  batch_size: 128
  epochs: 50

seed: 8888

output:
  save: true
  save_path : "/home/user/Documents/Experiments"
